### ISSUE TITLE
Avoiding AST and inserting the needed information into the source code

### ISSUE THREAD

**Issue by giltayar** [syg/ecmascript-binary-ast#16]
In the [meeting notes of the July TC39 meeting](https://esdiscuss.org/notes/2017-07-26), it was said that the space savings of the AST are minimal (compared to a minified version) - about 5%, so AST-ing the source code doesn't give a lot of benefit in terms of space-savings.

OTOH, the main (and considerable!) parse-time savings are accomplished from:
    * Knowing which variables are hoisted in a scope
    * Knowing which variables are "closed over" in a scope
    * Marking the presence of an `eval` or `with` in a scope
    * Early errors can de-optimize lazy parsing
    * Efficiencies when using binary instead of text characters.

Then again, defining an AST is a big endeavor, and may be fraught with politics, not to mention having to maintain it forever every time the language changes syntactically.

So given that an AST is problematic, and yet the parse-time savings from the proposal are considerable, I was wondering whether we could get the parse-time savings by using various markers _in the source code_ to add the information that is missing. In other words, the above points that are saved can be encoded into the source code using special comments or string directives. Something like:

```
//@efficient-parse

var x;
function f() {
  //@efficent-parse: hoisted[x]
  function use_x() {
    use(x);
  }

  var x;
}
```

(I wouldn't even call the above a strawman proposal, but just an incredibly rough draft to determine where I'm going here...)

This will probably enable parsers to deal with the first of the four points described in the proposal, but will not let them deal with the last point (efficiencies from the use of binary instead of text characters), given that it's still keeping the source code as source code with text characters. Unfortunately, I don't know how much of the performance improvements were gotten from each of the points above. It may be that 90% of the optimizations was because text was discarded, which makes my proposal of keeping the source code as text dead on arrival. :-) 

So I can't really know whether my proposal is efficient, but if it is, I believe the benefits of keeping the source code as source code and not going into the endeavor of defining an AST for JS _may_ outweigh the decrease in performance that keeping source code as text will make.

**Comment by Yoric** [comment]
@giltayar With this scheme, how would you allow lazy parsing?

**Comment by giltayar** [comment]
@Yoric - I don't know. If most of the efficiency of AST-ing the code is due to the parsing itself, then AST-ing may be the right solution, and mine definitely isn't. But if most of the efficiency is coming from having more information beforehand (e.g. which variables are hoisted and closed upon), then my solution (adding information to the code via comments) would be a preferable and easier solution.

So, yes - feel free to close the issue if parsing to AST gives the most benefit, but I would suggest adding this information explicitly to the proposal to make it clear to others.

**Comment by syg** [comment]
Thanks for your suggestions. (For lazy parsing, @Yoric, one could, for instance, record offsets into comments as well.)

Overall, I think text source with annotation comments, while decidedly less politically fraught and easier to implement, has at least these two issues:

- Parsing and lexing themselves are a big source of slowdown. There are independent performance wins from both encoding an AST *and* encoding annotations. We believe the current combination of both is the right amount of ambition. Specifying an AST will be difficult but I don't get the sense it is a political nonstarter as, e.g., bytecode would be.

- For consistency of behavior across implementations, the annotations as proposed here are deferred assertions. It is mandatory to check them; that is, they are not actually "hints". (I feel strongly that they should *not* be hints, because JS has enough silent performance cliffs as is, and I am loathe to add more.) Annotations expressed as comments will simply be no-ops in implementations that don't support them, which would lead to a pretty big behavior divergence.

@giltayar Again, thanks for your thoughts! Your suggestions is effectively a different proposal, so closing this issue.
